import { useMemo, useState, type Dispatch, type SetStateAction } from 'react';
import { Activity, Check, CircleCheck, HeartPulse, Play, Plus, ShieldCheck, Sparkles, Target, WandSparkles } from 'lucide-react';
import { completeGoal, createGoal, pickNextBestAction, type GoalPriority, type LifeGoal } from './lifeos-workspace';
import { ActivityList, GoalList, QuickActions, WorkspaceCard } from './LifeOSWorkspaceCards';

export const starterGoals: LifeGoal[] = [
  { id: 'starter-1', title: 'Protect the morning focus block', priority: 'high', completed: false },
  { id: 'starter-2', title: 'Move one important project forward', priority: 'medium', completed: false },
  { id: 'starter-3', title: 'Review weekly direction', priority: 'low', completed: false },
];

export function TodayWorkspace({ goals, onNavigate, onComplete }: { goals: LifeGoal[]; onNavigate: (section: string) => void; onComplete: (goal: LifeGoal) => void }) {
  const next = useMemo(() => pickNextBestAction(goals), [goals]);
  return <div className="workspace-page">
    <div className="workspace-hero"><div><span className="eyebrow"><Sparkles size={13}/> NEXT BEST ACTION</span><h1>{next ? next.title : 'Your day is clear.'}<span className="gradient-dot">.</span></h1><p>LifeOS combines your goals, priorities and current context into one focused starting point.</p></div><button className="primary-button" onClick={() => onNavigate('ask')}><Sparkles size={16}/> Ask LifeOS</button></div>
    <div className="workspace-grid two-up"><WorkspaceCard title="Today’s Focus" eyebrow="FOCUS"><div className="focus-panel"><div className="focus-icon"><Target size={19}/></div><div><strong>{next?.title || 'Choose a meaningful goal'}</strong><small>{next ? `${next.priority} priority · ready to act` : 'Add a goal from Life Goals'}</small></div></div><div className="stat-strip"><span><b>{goals.filter(g => g.completed).length}</b> completed</span><span><b>{goals.filter(g => !g.completed).length}</b> open</span><span><b>{Math.round((goals.filter(g => g.completed).length / Math.max(goals.length, 1)) * 100)}%</b> progress</span></div></WorkspaceCard><WorkspaceCard title="Quick Actions"><QuickActions actions={[{ label: 'Plan my day', description: 'Build a focused plan', icon: <Activity size={16}/>, onClick: () => onNavigate('day') }, { label: 'Work on a goal', description: 'Turn intent into steps', icon: <Target size={16}/>, onClick: () => onNavigate('goals') }, { label: 'Check my health', description: 'Open Health & Care', icon: <HeartPulse size={16}/>, onClick: () => onNavigate('health') }, { label: 'Research something', description: 'Explore a question', icon: <WandSparkles size={16}/>, onClick: () => onNavigate('research') }]} /></WorkspaceCard></div>
    <WorkspaceCard title="Recent LifeOS Activity"><ActivityList items={[{ title: 'LifeOS workspace opened', meta: 'Just now', status: 'ACTIVE' }, { title: 'Goal context prepared', meta: 'Today', status: 'READY' }, { title: 'Privacy controls available', meta: 'Always', status: 'ON' }]} /></WorkspaceCard>
    <div className="workspace-grid two-up"><WorkspaceCard title="Goal Progress"><GoalList goals={goals.slice(0, 4)} onComplete={onComplete}/></WorkspaceCard><WorkspaceCard title="Operating Principle" eyebrow="LIFEOS"><div className="principle"><ShieldCheck size={19}/><p><strong>Understand before acting.</strong><br/>LifeOS is designed to move from context and reasoning toward a useful next action while keeping the person in control.</p></div></WorkspaceCard></div>
  </div>;
}

export function GoalsWorkspace({ goals, setGoals }: { goals: LifeGoal[]; setGoals: Dispatch<SetStateAction<LifeGoal[]>> }) {
  const [title, setTitle] = useState(''); const [priority, setPriority] = useState<GoalPriority>('medium');
  const add = () => { if (!title.trim()) return; setGoals((current) => [...current, createGoal(title, priority)]); setTitle(''); };
  return <div className="workspace-page"><div className="page-head"><div><span className="eyebrow"><Target size={13}/> LIFE GOALS</span><h1>Make the important measurable.</h1><p>Goals are local V1 workspace state until a persistence API is connected.</p></div></div><WorkspaceCard title="Add a goal"><div className="goal-form"><input value={title} onChange={(e) => setTitle(e.target.value)} onKeyDown={(e) => e.key === 'Enter' && add()} placeholder="What matters right now?"/><select value={priority} onChange={(e) => setPriority(e.target.value as GoalPriority)}><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option><option value="urgent">Urgent</option></select><button className="primary-button" onClick={add}><Plus size={16}/> Add goal</button></div></WorkspaceCard><WorkspaceCard title="Your goals"><GoalList goals={goals} onComplete={(goal) => setGoals((current) => current.map((item) => item.id === goal.id ? completeGoal(item) : item))}/></WorkspaceCard></div>;
}

export function HealthCareWorkspace() {
  const [tasks, setTasks] = useState([{ id: 'h1', title: 'Log today’s wellness check-in', done: false }, { id: 'h2', title: 'Review upcoming appointment', done: false }, { id: 'h3', title: 'Take a short movement break', done: false }]);
  return <div className="workspace-page"><div className="workspace-hero compact"><div><span className="eyebrow"><HeartPulse size={13}/> HEALTH & CARE</span><h1>Your health, organized<span className="gradient-dot">.</span></h1><p>A private workspace for health context, care tasks and supportive routines.</p></div><div className="safe-badge"><ShieldCheck size={15}/> Privacy-first</div></div><div className="workspace-grid three-up"><WorkspaceCard title="Care Tasks"><div className="care-tasks">{tasks.map((task) => <button className={`care-task ${task.done ? 'done' : ''}`} key={task.id} onClick={() => setTasks((items) => items.map((x) => x.id === task.id ? {...x, done: !x.done} : x))}>{task.done ? <Check size={16}/> : <CircleCheck size={16}/>}<span>{task.title}</span></button>)}</div></WorkspaceCard><WorkspaceCard title="Health Context"><div className="metric-card"><span>Daily check-in</span><strong>Not recorded</strong><small>Add your own context when you’re ready.</small></div><div className="metric-card"><span>Care circle</span><strong>Private</strong><small>Keep sensitive information under your control.</small></div></WorkspaceCard><WorkspaceCard title="Safety"><div className="principle"><ShieldCheck size={20}/><p>LifeOS provides assistance and organization. It does not replace qualified medical professionals or emergency services.</p></div></WorkspaceCard></div></div>;
}

const agents = [{ id: 'planner', name: 'Day Planner', description: 'Turn priorities into a practical day plan.', status: 'Ready' }, { id: 'researcher', name: 'Research Assistant', description: 'Structure questions and research workflows.', status: 'Ready' }, { id: 'care', name: 'Care Organizer', description: 'Organize user-provided care tasks and context.', status: 'Review required' }];
export function AgentsWorkspace() { const [running, setRunning] = useState<string | null>(null); const [approved, setApproved] = useState<string[]>([]); const run = (id: string) => { setRunning(id); window.setTimeout(() => setRunning(null), 900); }; return <div className="workspace-page"><div className="page-head"><div><span className="eyebrow"><Sparkles size={13}/> AGENTS</span><h1>Specialists for focused work.</h1><p>V1 keeps consequential actions approval-gated. No autonomous external actions are performed here.</p></div></div><div className="agent-grid">{agents.map((agent) => <WorkspaceCard key={agent.id} title={agent.name} eyebrow={agent.status.toUpperCase()}><p className="agent-description">{agent.description}</p><div className="agent-actions"><button className="secondary-button" onClick={() => run(agent.id)} disabled={running === agent.id}>{running === agent.id ? 'Running…' : <><Play size={14}/> Run</>}</button>{approved.includes(agent.id) ? <span className="approved"><Check size={14}/> Approved</span> : <button className="ghost-button" onClick={() => setApproved((items) => [...items, agent.id])}>Review & approve</button>}</div></WorkspaceCard>)}</div></div>; }
